spring:
    cloud:
        sentinel:
            transport:
                dashboard: ${nft.sentinel.url}
                port: ${nft.sentinel.port}
            datasource:
                ds:
                    nacos:
                        server-addr: ${nft.nacos.server.url}
                        data-id:  ${nft.sentinel.nacos.data-id}
                        group-id: DEFAULT_GROUP
                        data-type: json
                        rule-type: flow  # 也可以是 degrade, param-flow, etc.